### PR TITLE
UI-8070 - Differentiate saved filters/widgets from filters/widgets within a dashboard

### PR DESCRIPTION
**Pull request by antoinetissier**
Some renaming to avoid any ambiguity.

### CODE REVIEW

**Comment by RaspberryChaos** [comment]
Looks good ! What do you think about changing the names in the `MigrationFunction` type ?

https://github.com/activeviam/activeui-migration/blob/63d5bf8462bffeb0eb835f8560f43db196c36ed9/src/migration.types.ts#L159-L163

**Comment by antoinetissier** [comment]
@RaspberryChaos actually I already did it. Did you have another place in mind ?

**Comment by RaspberryChaos** [comment]
> @RaspberryChaos actually I already did it. Did you have another place in mind ?

Sorry, my mistake. I missed that 😬

**Review by RaspberryChaos — APPROVED** [review]
Looks great! 🏁

**Pull request merged**
