### PR TITLE
UI-8176 - Make property `version` of `WidgetMetaData` mandatory

### PR DESCRIPTION
**Pull request by mailys-ds**
Close UI-8176.

### CODE REVIEW

**Review by antoinetissier — COMMENTED** [review]
In the current state of the PR, the `version` attribute is added on the fly  when reading the metadata, but it doesn't migrate anything.

Instead, each saved widget metadata record itself should be migrated.
`_getMetaData` doesn't need to be touched, and instead this can be done in `migrate_50_to_51`.

**Review by antoinetissier — COMMENTED** [review]
Let's remove the `console.log`s but otherwise it's the right idea 👍 
It'd be nice to add a unit test, and more importantly to test the CLI on a content server having saved widgets with/without a `version` attribute in their metadata.

**Comment by eliasinho** [comment]
I tried the with CLI and the migration works well!

**Review by antoinetissier — APPROVED** [review]
Looks good 👍

**Pull request merged**
